### ISSUE TITLE
Rename modular content to linked items

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/personalization-sdk-net#20]
Based on our vision regarding content items, we have to rename "Modular content element" to "Linked items element". From the Delivery SDK's point of view, it means that we are going to rename everything that contains "modularContent" to "linkedItems".

Checklist:
- [ ] updated all members (methods/properties/classes/...)
- [ ] updated .MD files
- [ ] updated tests
- [ ] updated github wiki

Keep in mind, that the Delivery API responses will remain the same. They'll still contain "modular_content".

Example implementation: https://github.com/Kentico/delivery-sdk-net/pull/130

Notes:
- this will result in a breaking change because of changes in public members -> [major version number has to be increased](https://semver.org/)
- plan your release so that the changes go live on 2018-10-03 and onwards.

**Comment by JamesMatchett** [comment]
Will happily do this.

just renaming all members, MD files, tests and the github wiki from "Modular content element" to "Linked items element"

**Comment by petrsvihlik** [comment]
Hi @JamesMatchett. Sorry, this issue has been submitted to this repository by mistake.

If you want to contribute to hacktoberfest, please feel free to pick any of the [`hacktoberfest`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Akentico+label%3Ahacktoberfest+archived%3Afalse+) labeled issues.

Or you can have a look in our per-stack backlogs here: https://github.com/orgs/Kentico/projects

**Comment by JamesMatchett** [comment]
No worries @petrsvihlik 👍 Thanks for the reply
